services:
  app:
    image: todo-front
    #ports:
      #- 8000:80 
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: todo-front # This will name the container hello-front-dev\

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend

  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    

  redis:
    image: redis:7-alpine  
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"        
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: 
      - ./redis_data:/data

  backend:
    image: todo-backend
    ports:
      - 3000:3000 
    build:
      context: ./todo-backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: todo-backend # This will name the container hello-front-dev
    environment: 
      - REDIS_URL=redis://redis_container:6379
      - MONGO_URL=mongodb://root:example@mongo_container:27017/the_database?authSource=admin
    depends_on:
      - mongo
      - redis

